apiVersion: v1
kind: BuildConfig
metadata:
  name: workshop2
    namespace: workshop2
spec:
  output:
    to:
      kind: ImageStreamTag
      name: workshop2:latest
  source:
    git:
      ref: master
      uri: https://github.com/zews79/workshop.git
    type: Git
  strategy:
    type: Docker
  triggers:
    - generic:
        secret: 7S4q8D6VU4KrucNg
      type: Generic
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: docker.io/nodeshift/centos7-s2i-nodejs
