apiVersion: v1
kind: Service
metadata:
  name: workshop2-svc
  namespace: workshop2
spec:
  selector:
    deploymentconfig: workshop2-dc
  ports:
    - name: nodejs
      protocol: TCP
      port: 8080
      targetPort: 8080
