apiVersion: v1
kind: DeploymentConfig
metadata:
  name: workshop2-dc
  namespace: workshop2
spec:
  replicas: 2
  selector:
    deploymentconfig: workshop2-dc
  strategy:
    type: Recreate
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - workshop2
        from:
          kind: ImageStreamTag
          name: workshop2:latest
      type: ImageChange
  template:
    metadata:
      labels:
        deploymentconfig: workshop2-dc
        name: workshop2
    spec:
      containers:
        - image: workshop2
          imagePullPolicy: Always
          name: workshop2
          ports:
            - containerPort: 8080
              name: nodejs
              protocol: TCP
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
